<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:ricevutans="http://comunicazioneconsensiricevuta.xsd.fse.ini.finanze.it" xmlns:richiestans="http://comunicazioneconsensirichiesta.xsd.fse.ini.finanze.it" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://comunicazioneconsensi.wsdl.fse.ini.finanze.it" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://comunicazioneconsensi.wsdl.fse.ini.finanze.it">
	<wsdl:types>
		<xsd:schema elementFormDefault="qualified">
			<xsd:import namespace="http://comunicazioneconsensirichiesta.xsd.fse.ini.finanze.it" schemaLocation="ComunicazioneConsensiRichiesta.xsd"/>
		</xsd:schema>
		<xsd:schema elementFormDefault="qualified">
			<xsd:import namespace="http://comunicazioneconsensiricevuta.xsd.fse.ini.finanze.it" schemaLocation="ComunicazioneConsensiRicevuta.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="ricevuta">
		<wsdl:part name="ComunicazioneConsensiRicevuta" element="ricevutans:ComunicazioneConsensiRicevuta"/>
	</wsdl:message>
	<wsdl:message name="richiesta">
		<wsdl:part name="ComunicazioneConsensiRichiesta" element="richiestans:ComunicazioneConsensiRichiesta"/>
	</wsdl:message>
	<wsdl:portType name="comunicazioneConsensiPT">
		<wsdl:operation name="comunicazioneConsensi">
			<wsdl:input message="tns:richiesta"/>
			<wsdl:output message="tns:ricevuta"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="comunicazioneConsensiBinding" type="tns:comunicazioneConsensiPT">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="comunicazioneConsensi">
			<soap:operation soapAction="http://comunicazioneconsensi.wsdl.fse.ini.finanze.it/ComunicazioneConsensi"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="fseComunicazioneConsensi">
		<wsdl:port name="fseComunicazioneConsensi" binding="tns:comunicazioneConsensiBinding">
			<soap:address location="http://localhost:9080/FseInsServicesWeb/services/fseComunicazioneConsensi"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
