<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>

<title></title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" >
</head>
<link href="css/styles.css" rel="stylesheet" type="text/css" media="all" />
<body>
<div id="container">
<!-- start container //-->
<div id="header"><h2>PHPFormBrowse</h2></div>
<div id="menubar">&nbsp;<div>
<div id="content">
<!-- start content //-->

